import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import fronius from '../public/Fronius Logo.webp'
import sungrow from '../public/sungrow.png'
import growatt from '../public/growatt.png'
import { useState } from 'react'
import navLogo from "../public/navlogo.png"

export default function Home() {

  const [isFroniusOpen, setisFroniusOpen] = useState(false)
  const [isSungrowOpen, setisSungrowOpen] = useState(false)
  const [isGrowattOpen, setisGrowattOpen] = useState(false)

  const [isbpharmcy, setIsbharmacy] = useState(false)
  const [ispg, setIspg] = useState(false)
  const [ismech, setIsmech] = useState(false)
  const [iscivil, setIscivil] = useState(false)

  const [isauditorium, setisauditorium] = useState(false)
  const [isbsh, setIsbsh] = useState(false)
  const [iscanteen, setIscanteen] = useState(false)
  const [isexam, setIsexam] = useState(false)


  const handleBoxOpen = (item) => {
    if (item == "fronius") {
      setisFroniusOpen(true)

    }
    if (item == "sungrow") {
      console.log("sungrow clicked")
      setisSungrowOpen(true)

    }
    if (item == "growatt") {
      setisGrowattOpen(true)

    }

  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.nav_bar}>
        <Image src={navLogo} width={150} height={110} alt="nav_logo"></Image>
        <h3> Solar Data Aquisation</h3>
      </div>
      <div className={styles.main_container} onClick={() => handleBoxOpen("fronius")}>
        <div className={styles.total_div}>
          <div className={styles.cmp_container}>
            <Image src={fronius} width={200} height={60} alt="img" className={styles.logo_img}></Image>
            <p>Fronius</p>
          </div>
          {isFroniusOpen &&
            <div className={styles.open_div}>
              <div className={styles.inner_div}>
                <p>BPharmacy</p>
                <button onClick={() => setIsbharmacy(!isbpharmcy)}>{isbpharmcy ? "Hide" : "View"}</button>
              </div>
              {isbpharmcy &&
                <div>
                  <p>Installed Capacity -  100kw</p>
                  <p>Output Power ---</p>
                </div>
              }
              <div className={styles.inner_div}>
                <p>PG Block</p>
                <button onClick={() => setIspg(!ispg)}>{ispg ? "Hide" : "View"}</button>
              </div>
              {ispg &&
                <div>
                  <p>Installed Capacity -  50kw</p>
                  <p>Output Power ---</p>
                </div>
              }
              <div className={styles.inner_div}>
                <p>Mechanical Block</p>
                <button onClick={() => setIsmech(!ismech)}>{ismech ? "Hide" : "View"}</button>
              </div>
              {ismech &&
                <div>
                  <p>Installed Capacity -  30kw</p>
                  <p>Output Power ---</p>
                </div>
              }
              <div className={styles.inner_div}>
                <p>Civil Block</p>
                <button onClick={() => setIscivil(!iscivil)}>{iscivil ? "Hide" : "View"}</button>
              </div>
              {iscivil &&
                <div>
                  <p>Installed Capacity -  20kw</p>
                  <p>Output Power ---</p>
                </div>
              }
            </div>}
        </div>

        <div className={styles.total_div}>
          <div className={styles.cmp_container} onClick={() => handleBoxOpen("sungrow")}>
            <Image src={sungrow} width={200} height={60} alt="img" className={styles.logo_img}></Image>
            <p>SunGrow</p>
          </div>
          {isSungrowOpen &&
            <div className={styles.open_div}>
              <div className={styles.inner_div}>
                <p>Auditorium</p>
                <button onClick={() => setisauditorium(!isauditorium)}>{isauditorium ? "Hide" : "View"}</button>
              </div>
              {isauditorium &&
                <div>
                  <p>Installed Capacity -  150kw</p>
                  <p>Output Power ---</p>
                </div>
              }

            </div>}
        </div>

        <div className={styles.total_div}>
          <div className={styles.cmp_container} onClick={() => handleBoxOpen("growatt")}>
            <Image src={growatt} width={200} height={60} alt="img" className={styles.logo_img}></Image>
            <p>Growatt</p>
          </div>
          {isGrowattOpen &&
            <div className={styles.open_div}>
              <div className={styles.inner_div}>
                <p>BSH Block</p>
                <button onClick={() => setIsbsh(!isbsh)}>{isbsh ? "Hide" : "View"}</button>
              </div>
              {isbsh &&
                <div>
                  <p>Installed Capacity - 90kw</p>
                  <p>Output Power ---</p>
                </div>
              }
              <div className={styles.inner_div}>
                <p>Canteen</p>
                <button onClick={() => setIscanteen(!iscanteen)}>{iscanteen ? "Hide" : "View"}</button>
              </div>
              {iscanteen &&
                <div>
                  <p>Installed Capacity -  30kw</p>
                  <p>Output Power ---</p>
                </div>
              }
              <div className={styles.inner_div}>
                <p>Exam Section</p>
                <button onClick={() => setIsexam(!isexam)}>{isexam ? "Hide" : "View"}</button>
              </div>
              {isexam &&
                <div>
                  <p>Installed Capacity -  30kw</p>
                  <p>Output Power    ---</p>
                </div>
              }



            </div>}
        </div>

      </div>
      <div className={styles.bottom_container}>
        <div>
          <p>Fronius Official Website :</p>
          <a href="https://www.solarweb.com/" target='_blank'> https://www.solarweb.com/  </a>
        </div>
        <div>
          <p>SunGrow Official Website :</p>
          <a href="https://www.portal.isolarcloud.com/" target='_blank'> https://www.portal.isolarcloud.com/ </a>
        </div>
        <div>
          <p>Growatt Official Website</p>
          <a href="https://www.server.growatt.com/" target='_blank'> https://www.server.growatt.com/  </a>
        </div>

      </div>

    </div>
  )
}
